name: Test Runner

on:
  workflow_dispatch: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testPackageRunnerInAllModes:
    name: Test package mode in all modes 📦✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2022.3.7f1
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v3
        with:
          lfs: true

      # Configure test runner
      - name: Run tests
        id: packageAllTests
        uses: ./
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: all
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+example.testpackage.*,-*Tests*'
          packageMode: true
          # Test implicit artifactsPath, by not setting it

      # Upload artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Package test results (all)
          path: ${{ steps.packageAllTests.outputs.artifactsPath }}
          retention-days: 14

      # Upload coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Package Coverage results (all)
          path: ${{ steps.packageAllTests.outputs.coveragePath }}
          retention-days: 14
