name: Test Runner

on:
  workflow_dispatch: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testPackageRunnerInAllModes:
    name: Test package mode in all modes 📦✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
     - uses: game-ci/unity-test-runner@v3
       with:
          packageMode: true
          projectPath: ./packageRoot
          githubToken: ${{ secrets.GITHUB_TOKEN }}        
          unityVersion: 2022.3.7f1
